# Generated by Django 3.1.13 on 2021-10-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20211004_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
